// This software has been modified from it's original version.
// original copyright notice was as follows:

// Copyright Vladimir Prus 2002-2004.
// Distributed under the Boost Software License, Version 1.0.
// (See accompanying file LICENSE_1_0.txt
// or copy at http://www.boost.org/LICENSE_1_0.txt)

/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/* The simplest usage of the library.
 */

#include <boost/program_options.hpp>
#include <boost/algorithm/string.hpp>
namespace po = boost::program_options;

#include <iostream>
#include <sstream>
using namespace std;

string hello_boost(int ac, char* av[])
{
    stringstream out;

    try {

        po::options_description desc("Allowed options");
        desc.add_options()
            ("help", "produce help message")
            ("change-world", "print args, but replace 'world' with 'boost'")
        ;

        po::variables_map vm;
        po::store(po::parse_command_line(ac, av, desc), vm);
        po::notify(vm);

        if (vm.count("help")) {
            out << desc << "\n";
        }

        if (vm.count("change-world")) {
            for (int i=1;i<ac;i++) {
		string arg(av[i]);
                boost::replace_all( arg, "--change-world", "" );
                boost::replace_all( arg, "world", "boost" );
                out << arg << " ";
            }
        }
    }
    catch(exception& e) {
        out << "error: " << e.what() << "\n";
    }
    catch(...) {
        out << "Exception of unknown type!\n";
    }

    return out.str();
}

/*
//for testing
//g++ first.cpp -lboost_program_options  && ./a.out --change-world hello world

main(int argc, char *argv[] ) {
    cout << "ret: " << hello_boost(argc,argv) << endl;
}
*/
